backend:
  name: github
  repo: lechiluan/lechiluan.github.io
  branch: main
  base_url: https://your-oauth-provider.com # Bạn sẽ cần thay thế link này sau khi cài đặt OAuth Gateway

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          date_format: "YYYY-MM-DD",
          time_format: false,
        }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Cover Image URL",
          name: "image",
          widget: "string",
          hint: "Dán link ảnh từ Unsplash hoặc link web khác",
        }
      - { label: "Body", name: "body", widget: "markdown" }
